### ISSUE TITLE
Generate binder and move pyOCCT specific items to that project

### ISSUE THREAD

**Issue by trelau** [LaughlinResearch/pyOCCT_binder#2]
For example, [this](https://github.com/LaughlinResearch/pyOCCT_binder/blob/5ab79c9e9eda5173236d3c2bf3b96fd9b0664df6/generate/run.py#L160) could be an input when building via CI in the pyOCCT project. The `config.txt` could (should?) be moved to the pyOCCT project and maintained there. Eventually, this project will be used for both pyOCCT and a separate "pySMESH" project.

**Comment by frmdstryr** [comment]
Agree, that sounds like a good way to do it.

**Comment by trelau** [comment]
done
